services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  spring:
    image: trissss/influy
    container_name: influy
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/nginx/influy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - spring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - spring
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

volumes:
  grafana-storage: